# Generated by Django 2.1.7 on 2019-03-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blogger'),
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Add the blog content', max_length='1000', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.TextField(help_text='Enter a title for the blog post', max_length='100', null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(help_text='Description about the blogger', max_length='200', null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='name',
            field=models.TextField(help_text="Blogger's name", max_length='30', null=True),
        ),
    ]
