# Generated by Django 2.1.7 on 2019-03-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190328_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Enter a title for the blog post', max_length=50, null=True),
        ),
    ]
