# Generated by Django 2.1.7 on 2019-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190328_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Add the blog content', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(help_text='Description about the blogger', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='name',
            field=models.TextField(help_text="Blogger's name", max_length=30, null=True),
        ),
    ]
