# Generated by Django 2.1.7 on 2019-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190328_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Enter a title for the blog post', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='name',
            field=models.CharField(help_text="Blogger's name", max_length=50, null=True),
        ),
    ]
